version: '3.8'

services:
  frontend:
    image: stacklabdigital/orbitchat:develop
    working_dir: /app
    environment:
      - PORT=4000
      - VITE_API_URL=http://api.orbitchat.io
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - VITE_WS_URL=wss://api.orbitchat.io
      - VITE_GRAPHQL_URL=http://api.orbitchat.io/graphql
      - DATABASE_URL=postgresql://postgres:PT99874166@postgres:5432/orbitchatv2?schema=public
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=PT99874166
      - DB_PORT=5432
      - DB_SCHEMA=public
      - JWT_SECRET=1234
      - FRONTEND_URL=https://app.orbitchat.io
      - HOST=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run preview -- --host 0.0.0.0 --port 5173
    networks:
      - pedetudo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.orbitchat_frontend.rule=Host(`app.orbitchat.io`)
        - traefik.http.routers.orbitchat_frontend.entrypoints=websecure
        - traefik.http.routers.orbitchat_frontend.tls.certresolver=letsencryptresolver
        - traefik.http.routers.orbitchat_frontend.service=orbitchat_frontend
        - traefik.http.services.orbitchat_frontend.loadbalancer.server.port=5173
        - traefik.http.services.orbitchat_frontend.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.orbitchat_frontend.middlewares=sslheader@docker

  backend:
    image: stacklabdigital/orbitchat:develop
    working_dir: /app/backend
    environment:
      - PORT=4000
      - VITE_API_URL=http://api.orbitchat.io
      - NODE_ENV=postgres
      - REDIS_URL=redis://redis:6379
      - VITE_WS_URL=wss://api.orbitchat.io
      - VITE_GRAPHQL_URL=http://api.orbitchat.io/graphql
      - DATABASE_URL=postgresql://postgres:PT99874166@postgres:5432/orbitchatv2?schema=public
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=PT99874166
      - DB_PORT=5432
      - DB_SCHEMA=public
      - JWT_SECRET=1234
      - FRONTEND_URL=https://app.orbitchat.io
      - HOST=0.0.0.0
    restart: unless-stopped
    command: >
      sh -c "
        chmod +x ./init.sh &&
        ./init.sh
      "
    networks:
      - pedetudo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.orbitchat_backend.rule=Host(`api.orbitchat.io`)
        - traefik.http.routers.orbitchat_backend.entrypoints=websecure
        - traefik.http.routers.orbitchat_backend.tls.certresolver=letsencryptresolver
        - traefik.http.routers.orbitchat_backend.service=orbitchat_backend
        - traefik.http.services.orbitchat_backend.loadbalancer.server.port=4000
        - traefik.http.services.orbitchat_backend.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.orbitchat_backend.middlewares=sslheader@docker
        - traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
        - traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*

networks:
  pedetudo:
    external: true
    name: pedetudo