version: '3.8'

services:
  frontend:
    image: stacklabdigital/orbitchat:develop
    working_dir: /app
    environment:
      - VITE_API_URL=https://orbit-api.stacklab.digital
      - NODE_ENV=production
      - HOST=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run preview -- --host 0.0.0.0 --port 5173
    networks:
      - pedetudo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.orbitchat_frontend.rule=Host(`orbit.stacklab.digital`)
        - traefik.http.routers.orbitchat_frontend.entrypoints=websecure
        - traefik.http.routers.orbitchat_frontend.tls.certresolver=letsencryptresolver
        - traefik.http.routers.orbitchat_frontend.service=orbitchat_frontend
        - traefik.http.services.orbitchat_frontend.loadbalancer.server.port=5173
        - traefik.http.services.orbitchat_frontend.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.orbitchat_frontend.middlewares=sslheader@docker

  backend:
    image: stacklabdigital/orbitchat:develop
    working_dir: /app/backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:PT99874166@postgres:5432/orbitchat?schema=public
      - JWT_SECRET=1234
      - FRONTEND_URL=https://orbit.stacklab.digital
      - HOST=0.0.0.0
    restart: unless-stopped
    command: npm run dev
    networks:
      - pedetudo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.orbitchat_backend.rule=Host(`orbit-api.stacklab.digital`)
        - traefik.http.routers.orbitchat_backend.entrypoints=websecure
        - traefik.http.routers.orbitchat_backend.tls.certresolver=letsencryptresolver
        - traefik.http.routers.orbitchat_backend.service=orbitchat_backend
        - traefik.http.services.orbitchat_backend.loadbalancer.server.port=4000
        - traefik.http.services.orbitchat_backend.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.orbitchat_backend.middlewares=sslheader@docker

networks:
  pedetudo:
    external: true
    name: pedetudo